title: Rupin Solanki
description: DevOps and Site Reliability Engineer
url: "https://rupinsolanki07.github.io"
baseurl: "/rupinsolanki07"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - blog.md
  - projects.md
